export const weatherTypes = {
  GET_CURRENT_WEATHER: '[WEATHER]: GET_CURRENT_WEATHER',
  GET_FORECAST_5DAYS: '[WEATHER]: GET_FORECAST_5DAYS',
  SET_COORDINATES: '[WEATHER]: SET_COORDINATES',
  IS_LOADING: '[WEATHER]: IS_LOADING',
  SELECT_LIST_WEATHER: '[WEATHER]: SELECT_LIST_WEATHER',
  SET_CURRENT_WEATHER: '[WEATHER]: SET_CURRENT_WEATHER',
};
